# Generated by Django 6.1 on 2026-09-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Explore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField()),
                ('media', models.ImageField(upload_to='img/')),
                ('content', models.TextField()),
            ],
        ),
    ]
