# Generated by Django 6.1 on 2026-09-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='more',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField()),
                ('media', models.ImageField(upload_to='img/')),
                ('content', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Explore',
        ),
    ]
