# Generated by Django 6.1 on 2026-09-04 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_app', '0002_more_delete_explore'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='more',
            new_name='Explore',
        ),
    ]
