# Generated by Django 6.1 on 2026-09-04 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_app', '0003_rename_more_explore'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Explore',
            new_name='About',
        ),
    ]
