# Generated by Django 6.1 on 2026-09-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_app', '0004_rename_explore_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ImageField(upload_to='img/')),
                ('header', models.TextField()),
                ('context', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
    ]
